version: '2.1'
services:
    executari-com:
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            - APIFY_LOCAL_STORAGE_DIR=/storage
            - APIFY_MEMORY_MBYTES=2048
            - APIFY_HEADLESS=1
            - APIFY_DEFAULT_DATASET_ID=executari-com
            - APIFY_DEFAULT_KEY_VALUE_STORE_ID=executari-com
            - APIFY_DEFAULT_REQUEST_QUEUE_ID=executari-com
            - START_URL=https://www.executari.com/lista_bunuri.php?cat=6&judet=50&pmax=100000&p=1
            - PSEUDO_URL=https://www.executari.com/lista_bunuri.php?cat=6&judet=50&pmax=100000&p=[([\\d]+)]
            - DOMAIN=https://www.executari.com
            - SAMPLE=0
        volumes:
            - ./../storage:/storage

    uniuneaexecutorilor-ro:
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            - APIFY_LOCAL_STORAGE_DIR=/storage
            - APIFY_MEMORY_MBYTES=2048
            - APIFY_HEADLESS=1
            - APIFY_DEFAULT_DATASET_ID=uniuneaexecutorilor-ro
            - APIFY_DEFAULT_KEY_VALUE_STORE_ID=uniuneaexecutorilor-ro
            - APIFY_DEFAULT_REQUEST_QUEUE_ID=uniuneaexecutorilor-ro
            - START_URL=https://www.registru.uniuneaexecutorilor.ro/judet/bucuresti/categorie/teren?sort=pub.auction_date&direction=desc&page=1
            - PSEUDO_URL=https://www.registru.uniuneaexecutorilor.ro/judet/bucuresti/categorie/teren?sort=pub.auction_date&direction=desc&page=[([\\d]+)]
            - DOMAIN=https://www.registru.uniuneaexecutorilor.ro
            - SAMPLE=0
        volumes:
            - ./../storage:/storage

    olx-ro:
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            - APIFY_LOCAL_STORAGE_DIR=/storage
            - APIFY_MEMORY_MBYTES=2048
            - APIFY_HEADLESS=1
            - APIFY_DEFAULT_DATASET_ID=olx-ro
            - APIFY_DEFAULT_KEY_VALUE_STORE_ID=olx-ro
            - APIFY_DEFAULT_REQUEST_QUEUE_ID=olx-ro
            - START_URL=https://www.olx.ro/imobiliare/terenuri/bucuresti-ilfov-judet/q-Bucurestii-Noi/?search%5Bfilter_float_price%3Afrom%5D=30000&search%5Bfilter_float_price%3Ato%5D=100000&search%5Bfilter_enum_extravilan_interavilan%5D%5B0%5D=intravilan&search%5Bfilter_float_m%3Afrom%5D=200&search%5Bfilter_float_m%3Ato%5D=500&search%5Border%5D=created_at%3Adesc&page=1
            - PSEUDO_URL=https://www.olx.ro/imobiliare/terenuri/bucuresti-ilfov-judet/q-Bucurestii-Noi/?search%5Bfilter_float_price%3Afrom%5D=30000&search%5Bfilter_float_price%3Ato%5D=100000&search%5Bfilter_enum_extravilan_interavilan%5D%5B0%5D=intravilan&search%5Bfilter_float_m%3Afrom%5D=200&search%5Bfilter_float_m%3Ato%5D=500&search%5Border%5D=created_at%3Adesc&page=[([\\d]+)]
            - DOMAIN=https://www.olx.ro
            - SAMPLE=0
        volumes:
            - ./../storage:/storage

    imobiliare-ro:
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            - APIFY_LOCAL_STORAGE_DIR=/storage
            - APIFY_MEMORY_MBYTES=2048
            - APIFY_HEADLESS=1
            - APIFY_DEFAULT_DATASET_ID=imobiliare-ro
            - APIFY_DEFAULT_KEY_VALUE_STORE_ID=imobiliare-ro
            - APIFY_DEFAULT_REQUEST_QUEUE_ID=imobiliare-ro
            - START_URL=https://www.imobiliare.ro/vanzare-terenuri-constructii/bucuresti?id=28740727&pagina=1
            - PSEUDO_URL=https://www.imobiliare.ro/vanzare-terenuri-constructii/bucuresti?id=28740727&pagina=[([\\d]+)]
            - DOMAIN=https://www.imobiliare.ro
            - SAMPLE=0
        volumes:
            - ./../storage:/storage

    homezz-ro:
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            - APIFY_LOCAL_STORAGE_DIR=/storage
            - APIFY_MEMORY_MBYTES=2048
            - APIFY_HEADLESS=1
            - APIFY_DEFAULT_DATASET_ID=homezz-ro
            - APIFY_DEFAULT_KEY_VALUE_STORE_ID=homezz-ro
            - APIFY_DEFAULT_REQUEST_QUEUE_ID=homezz-ro
            - START_URL=https://homezz.ro/anunturi_terenuri_de-vanzare_in-bucuresti-if_pret-de-la-30000-pana-la-100000-eur_ordonare-dupa-data-descrescator_fara-poze.html?tsf=200&tst=300&tt=1&tt2=1
            - PSEUDO_URL=https://homezz.ro/anunturi_terenuri_de-vanzare_in-bucuresti-if_pret-de-la-30000-pana-la-100000-eur_ordonare-dupa-data-descrescator_fara-poze_[([\\d]+)].html?tsf=200&tst=300&tt=1&tt2=1
            - DOMAIN=https://homezz.ro
            - SAMPLE=0
        volumes:
            - ./../storage:/storage

    homezz-ro2:
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            - APIFY_LOCAL_STORAGE_DIR=/storage
            - APIFY_MEMORY_MBYTES=2048
            - APIFY_HEADLESS=1
            - APIFY_DEFAULT_DATASET_ID=homezz-ro2
            - APIFY_DEFAULT_KEY_VALUE_STORE_ID=homezz-ro2
            - APIFY_DEFAULT_REQUEST_QUEUE_ID=homezz-ro2
            - START_URL=https://homezz.ro/anunturi_case-vile_de-vanzare_in-bucuresti-if_pret-pana-la-200000_ordonare-dupa-data-descrescator_fara-poze.html?ro=3,4,5&redt=170&tsf=200&ba=2,3
            - PSEUDO_URL=https://homezz.ro/anunturi_case-vile_de-vanzare_in-bucuresti-if_pret-pana-la-200000-eur_ordonare-dupa-data-descrescator_fara-poze_[([\\d]+)].html?ro=3,4,5&redt=170&tsf=200&ba=2,3
            - DOMAIN=https://homezz.ro
            - SAMPLE=0
        volumes:
            - ./../storage:/storage

    publi24-ro:
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            - APIFY_LOCAL_STORAGE_DIR=/storage
            - APIFY_MEMORY_MBYTES=2048
            - APIFY_HEADLESS=1
            - APIFY_DEFAULT_DATASET_ID=publi24-ro
            - APIFY_DEFAULT_KEY_VALUE_STORE_ID=publi24-ro
            - APIFY_DEFAULT_REQUEST_QUEUE_ID=publi24-ro
            - START_URL=https://www.publi24.ro/anunturi/imobiliare/de-vanzare/terenuri/bucuresti/?minprice=30000&maxprice=100000&pag=1
            - PSEUDO_URL=https://www.publi24.ro/anunturi/imobiliare/de-vanzare/terenuri/bucuresti/?minprice=30000&maxprice=100000&pag=[([\\d]+)]
            - DOMAIN=https://www.publi24.ro
            - SAMPLE=0
        volumes:
            - ./../storage:/storage

    publi24-ro2:
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            - APIFY_LOCAL_STORAGE_DIR=/storage
            - APIFY_MEMORY_MBYTES=2048
            - APIFY_HEADLESS=1
            - APIFY_DEFAULT_DATASET_ID=publi24-ro2
            - APIFY_DEFAULT_KEY_VALUE_STORE_ID=publi24-ro2
            - APIFY_DEFAULT_REQUEST_QUEUE_ID=publi24-ro2
            - START_URL=https://www.publi24.ro/anunturi/imobiliare/de-vanzare/case/bucuresti/?minprice=50000&maxprice=200000
            - PSEUDO_URL=https://www.publi24.ro/anunturi/imobiliare/de-vanzare/case/bucuresti/?minprice=50000&maxprice=200000&pag=[([\\d]+)]
            - DOMAIN=https://www.publi24.ro
            - SAMPLE=0
        volumes:
            - ./../storage:/storage

    imo-nord-ro:
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            - APIFY_LOCAL_STORAGE_DIR=/storage
            - APIFY_MEMORY_MBYTES=2048
            - APIFY_HEADLESS=1
            - APIFY_DEFAULT_DATASET_ID=imo-nord-ro
            - APIFY_DEFAULT_KEY_VALUE_STORE_ID=imo-nord-ro
            - APIFY_DEFAULT_REQUEST_QUEUE_ID=imo-nord-ro
            - START_URL=https://www.imo-nord.ro/oferte-imobiliare/sale/land/?count=12&keyw=&land_type=1&n=0#product-list
            - PSEUDO_URL=https://www.imo-nord.ro/oferte-imobiliare/sale/land/?count=12&keyw=&land_type=1&n=[([\\d]+)]#product-list
            - DOMAIN=https://www.imo-nord.ro
            - SAMPLE=0
        volumes:
            - ./../storage:/storage

    # imo-nord-ro2:
    #     build:
    #         context: .
    #         dockerfile: Dockerfile
    #     environment:
    #         - APIFY_LOCAL_STORAGE_DIR=/storage
    #         - APIFY_MEMORY_MBYTES=2048
    #         - APIFY_HEADLESS=1
    #         - APIFY_DEFAULT_DATASET_ID=imo-nord-ro2
    #         - APIFY_DEFAULT_KEY_VALUE_STORE_ID=imo-nord-ro2
    #         - APIFY_DEFAULT_REQUEST_QUEUE_ID=imo-nord-ro2
    #         - START_URL=https://www.imo-nord.ro/oferte-imobiliare/sale/house/
    #         - PSEUDO_URL=https://www.imo-nord.ro/oferte-imobiliare/sale/house/?=&count=12&keyw=&n=[([\\d]+)]
    #         - DOMAIN=https://www.imo-nord.ro
    #         - SAMPLE=0
    #     volumes:
    #         - ./../storage:/storage

    brizaland-ro:
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            - APIFY_LOCAL_STORAGE_DIR=/storage
            - APIFY_MEMORY_MBYTES=2048
            - APIFY_HEADLESS=1
            - APIFY_DEFAULT_DATASET_ID=brizaland-ro
            - APIFY_DEFAULT_KEY_VALUE_STORE_ID=brizaland-ro
            - APIFY_DEFAULT_REQUEST_QUEUE_ID=brizaland-ro
            - START_URL=http://www.brizaland.ro/brizaland/ro/lista/vanzari-terenuri/--0-0-data-desc/1/-/
            - PSEUDO_URL=http://www.brizaland.ro/brizaland/ro/lista/vanzari-terenuri/--0-0-data-desc/[([\\d]+)]/-/
            - DOMAIN=http://www.brizaland.ro
            - SAMPLE=0
        volumes:
            - ./../storage:/storage

    imobiliarenord-ro:
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            - APIFY_LOCAL_STORAGE_DIR=/storage
            - APIFY_MEMORY_MBYTES=2048
            - APIFY_HEADLESS=1
            - APIFY_DEFAULT_DATASET_ID=imobiliarenord-ro
            - APIFY_DEFAULT_KEY_VALUE_STORE_ID=imobiliarenord-ro
            - APIFY_DEFAULT_REQUEST_QUEUE_ID=imobiliarenord-ro
            - START_URL=https://imobiliarenord.ro/listings/terenuri/
            - PSEUDO_URL=https://imobiliarenord.ro/listings/terenuri/page/[([\\d]+)]/
            - DOMAIN=https://imobiliarenord.ro
            - SAMPLE=0
        volumes:
            - ./../storage:/storage

    brizaland-ro2:
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            - APIFY_LOCAL_STORAGE_DIR=/storage
            - APIFY_MEMORY_MBYTES=2048
            - APIFY_HEADLESS=1
            - APIFY_DEFAULT_DATASET_ID=brizaland-ro2
            - APIFY_DEFAULT_KEY_VALUE_STORE_ID=brizaland-ro2
            - APIFY_DEFAULT_REQUEST_QUEUE_ID=brizaland-ro2
            - START_URL=http://www.brizaland.ro/brizaland/ro/lista/vanzari-case-vile/--0-0-data-desc/1/-/
            - PSEUDO_URL=http://www.brizaland.ro/brizaland/ro/lista/vanzari-case-vile/--0-0-data-desc/[([\\d]+)]/-/
            - DOMAIN=http://www.brizaland.ro
            - SAMPLE=0
        volumes:
            - ./../storage:/storage

    lajumatate-ro:
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            - APIFY_LOCAL_STORAGE_DIR=/storage
            - APIFY_MEMORY_MBYTES=2048
            - APIFY_HEADLESS=1
            - APIFY_DEFAULT_DATASET_ID=lajumatate-ro
            - APIFY_DEFAULT_KEY_VALUE_STORE_ID=lajumatate-ro
            - APIFY_DEFAULT_REQUEST_QUEUE_ID=lajumatate-ro
            - START_URL=https://lajumate.ro/anunturi_terenuri_in-bucuresti-if_pret-pana-la-100000.html?tt=1&tsf=200&tst=500&tt2=1
            - PSEUDO_URL=https://lajumate.ro/anunturi_terenuri_in-bucuresti-if_pret-pana-la-100000-eur_[([\\d]+)].html?tt=1&tsf=200&tst=500&tt2=1
            - DOMAIN=https://lajumate.ro
            - SAMPLE=0
        volumes:
            - ./../storage:/storage
